### ISSUE TITLE
Implement Opus

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#18]
Find and use an implementation for the Opus audio codec (http://www.opus-codec.org/).
Implement as AudioProcessor

**Comment by Kaayy-J** [comment]
- Add header-guard
- combine  decoder/encoder into one processor
- use new features,see #32 to retrieve configuration and modify buffer-size

**Comment by J0n8s** [comment]
- ~~Add header-guard~~ 829f62164ab68b84637e3f826aa709e24b371a46
- ~~combine  decoder/encoder into one processor~~ 829f62164ab68b84637e3f826aa709e24b371a46
- use new features,see #32 to retrieve configuration and modify buffer-size

**Comment by doe300** [comment]
- Override configure(AudioConfiguration) to initialize encoder/decoder objects
- ProcessorOpus::processOutputData needs to return number of bytes (samples \* sizeOfSample \* channels?)
- ProcessorOpus::processOutputData needs to write numberOfDecodedSamples into userData->nBufferFrames
- remove buffer-size workaround and use correct buffer-size (outputBufferByteSize) for decoder

**Comment by J0n8s** [comment]
- use new features,see #32 to retrieve configuration and modify buffer-size

see #37 
- Override configure(AudioConfiguration) to initialize encoder/decoder objects

see #36 
- ProcessorOpus::processOutputData needs to return number of bytes (samples \* sizeOfSample \* channels

ProcessorOpus::processOutputData cant return number of bytes correctly because he has no acces to the correct number of channels because this parameter from AudioConfiguration is not provided in this methode, so (samples \* sizeOfSample \* channels) cant be calculated, perhaps something for #32 
- ~~ProcessorOpus::processOutputData needs to write numberOfDecodedSamples into userData->nBufferFrames~~ 7fc2e647914bb685a0b8e958a42682dc9a682721
- ~~remove buffer-size workaround and use correct buffer-size (outputBufferByteSize) for decoder~~ 7fc2e647914bb685a0b8e958a42682dc9a682721

**Comment by doe300** [comment]
@J0n8s In ProcessorOpus.cpp, could you should write your error-messages into std::cerr
Also, when you are done, delete the opus-branch

**Comment by J0n8s** [comment]
- ~~use new features,see #32 to retrieve configuration and modify buffer-size~~ 05daca321dd00fd87f5dcd089db0fa544ac81cc5
- ~~Override configure(AudioConfiguration) to initialize encoder/decoder objects~~ 
  6a1146439a4c41233ecd267f668b7d83d49a0c69
- ~~ProcessorOpus::processOutputData needs to return number of bytes (samples \* sizeOfSample \* channels~~

ProcessorOpus::processOutputData now gets the OutputDeviceChannels from the configure methode which saves the information into a private variable 05daca321dd00fd87f5dcd089db0fa544ac81cc5
- ~~In ProcessorOpus.cpp, could you should write your error-messages into std::cerr~~ 

Thanks for the hint @doe300 e636ba9ec59d160bf459b7f350de9cd1b62a09bf
- ~~Also, when you are done, delete the opus-branch~~

done

**Comment by J0n8s** [comment]
Next enhancement opus encode/decode`float`
