### ISSUE TITLE
RTPPackage

### ISSUE THREAD

**Issue by doe300** [doe300/OHMComm#22]
Few things to clear up:
- Why was the CSRCs and the "old" read/write-methods discarded?
- Why not set package-data once (i.e. in constructor)?
- What are all those void\* for?

Few things to fix:
- need to generate random SSRC and reuse it for every sent package
- need to generate random initial timestamp and increment on every call (time linear!)

**Comment by Kaayy-J** [comment]
As far as I know CSRC is optional. Therefore I removed it. It should not be a problem to add it later, when it is actually needed.

In order to keep the structure clean, I removed the methods within. I think they better suit in a class with an concrete object of RTPHeader.

My thoughts for the RTPPackage class:
- class should work as a standalone class (no dependencies)
- optimized for our purpose (performance - It is not very smart to generate a new object for every call and then dispose it. We need to generate many RTPPackages on the fly and then send over the network. Why not generate one RTPPackage and overwrite it over and over again after it has been transmitted...)

void_-Pointers act same as char_-Pointers. I guess 1 char = 1 byte on every system hence void\* or char\* should be used in the project.

**Comment by Kaayy-J** [comment]
RTPPackage already has a random generator, which probably could be reused:

std::mt19937 randomGenerator;

**Comment by doe300** [comment]
Okay, so we just leave the CSRCs be for now.
@Kaayy-J, could you add methods to RTPPackage to get/set an RTPHeader and its data.

**Comment by Kaayy-J** [comment]
Actually they have been implemented already. For example:

auto getNewRTPPackage(void\* data)->void_;
auto getDataFromRTPPackage(void *rtpPackage) -> void_; 
auto getHeaderFromRTPPackage(void _rtpPackage) -> void_;

**Comment by Kaayy-J** [comment]
I have to admit that I should have added a documentation to make that clear. 
When im back at home, I will add a short documentation.

**Comment by Kaayy-J** [comment]
@doe300 added short documentation about the RTPPackage class
It is probably not the best solution, but it is good one. If you have any question feel free to ask me.
